# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Design Portefolio
email: aosparesdetres@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Communication Designer, freelance, web designer, UI/UX designer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thegaspar.com" # the base hostname & protocol for your site
twitter_username: onerootzreggae
github_username: rootzreggae

# defaults:
#   -
#     scope:
#       path: "projects"
#       type: "pages" # previously `page` in Jekyll 2.2.
#     values:
#       layout: "projects" # overrides previous default layout


# Build settings
markdown: kramdown
exclude:
  - package.json
  - node_modules
  - gulpfile.js
